---
abstract: 'a perl module for comparing Artifact versions exactly like Maven does.'
author:
  - 'Thomas Cazali <pandragon@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141520'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Java-Maven-Artifact-Version
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Scalar::Util: '0'
  perl: '5.006'
resources:
  Type: git
  Url: git@github.com:apendragon/Java-Maven-Artifact-Version.git
  Web: https://github.com/apendragon/Java-Maven-Artifact-Version.git
version: '1.00'
x_bugtracker:
  mailto: pandragon@cpan.org
  web: https://github.com/apendragon/Java-Maven-Artifact-Version/issues
x_homepage: https://github.com/apendragon/Java-Maven-Artifact-Version/wiki
