---
abstract: 'a perl module for comparing Artifact versions exactly like Maven does.'
author:
  - 'Thomas Cazali <pandragon@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141520'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Java-Maven-Artifact-Version
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Scalar::Util: '0'
  perl: '5.008008'
resources:
  bugtracker: https://github.com/apendragon/Java-Maven-Artifact-Version/issues
  homepage: https://github.com/apendragon/Java-Maven-Artifact-Version/wiki
  license: https://github.com/apendragon/Java-Maven-Artifact-Version/blob/master/LICENSE
  repository: git://github.com/apendragon/Java-Maven-Artifact-Version.git
version: '1.000001'
